### ISSUE TITLE
Does it support img tag...?

### ISSUE THREAD

**Issue by lovebdsobuj** [chiuki/advanced-textview#4]

**Comment by chiuki** [comment]
Not sure what you mean, but answer is most likely no.

**Comment by lovebdsobuj** [comment]
I tried like these...
```
<img src="file:///android_asset/image/icon.png"> 
<img src=\"file:///android_asset/image/icon.png\"> 
<img src="file:///android_res/drawable-hdpi/splash.png"/> 
<img src="data:image/png;base64,iVBORw0KGgoAAAANS

```
![device-2016-02-24-111432](https://cloud.githubusercontent.com/assets/10352682/13304071/0135db08-db7d-11e5-89df-e6a0baf968d8.png)

But not yet done.

**Comment by chiuki** [comment]
You need an `Html.ImageGetter`. See `FromHtmlActivity.java` for an example.

**Comment by lovebdsobuj** [comment]
@chiuki another topic, I have plan make an Android Alphabet Apps for Bengali kids, 
I maked a online web page for that. [Bangla Bornomala/Alphabet](http://appsforbd.com/bornomala)

I want make it native android app, do you able to help me...?

**Comment by chiuki** [comment]
That is out of scope of this project.

**Comment by lovebdsobuj** [comment]
I know & understand that... But I just share with you. Hope you understand me.
